[package]
name = "rmidirs"
version = "0.1.0"
edition = "2021"
rust_version = "1.66.0"


[lib]
crate-type = ["cdylib", "rlib"]

[dependencies]
lazy_static = "1.4.0"
serde_json = "1.0"

[dependencies.wasm-bindgen]
version = "0.2.74"

[dependencies.cfg-if]
version = "1.0.0"